services:
  - type: web
    name: phishing-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false

databases:
  - name: phishing-detector-db
    databaseName: mailguard
    user: phishing_detector_user
