services:
  - type: web
    name: phishing-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        value: 9LN36ZsohRVZNKd8HqPDUDBTLjr4l8oTulz769uB4zw
      - key: MONGO_URI
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: EMAIL_ADDRESS
        value: mailguard849@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
